Keratech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from .sitemaps import ProductSitemap, StaticViewSitemap, TypeSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'types': TypeSitemap,
    'products': ProductSitemap,
}

handler404 = 'core.views.error_404'

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
    ),

    path(
        'chaining/',
        include('smart_selects.urls'),
    ),
    path(
        'ckeditor/',
        include('ckeditor_uploader.urls'),
    ),
    path(
        'djeym/',
        include('djeym.urls', namespace='djeym'),
    ),

    path(
        '',
        include('homepage.urls'),
        name='homepage',
    ),
    path(
        'product/',
        include('product.urls'),
        name='product',
    ),
    path(
        'about/', include('about.urls'),
        name='about',
    ),

    path(
        '', include('core.urls'),
        name='core',
    ),
    path(
        'sitemap.xml',
        sitemap, {'sitemaps': sitemaps},
    )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

core/urls.py
from django.urls import path

from core import views

urlpatterns = [
    path('robots.txt', views.robots_txt, name='robots_txt'),
]

homepage/urls.py
from django.urls import path

from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

product/urls.py
from django.urls import path

from product import views

app_name = 'product'

urlpatterns = [
    path('type/<slug:slug>/', views.type_detail, name='type_detail'),
    path('', views.product_list, name='product_list'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

homepage/models.py
from django.db import models

from core.models import BaseImgModel, BaseModel
from core.validators import validate_image_aspect_ratio


def validate_image_aspect_ratio_func(image):
    validate_image_aspect_ratio(image, (16, 9))


class CarouselImg(BaseModel, BaseImgModel, models.Model):
    def __str__(self):
        return self.photo.url

    class Meta:
        verbose_name = 'Изображение карусели'
        verbose_name_plural = 'Изображения карусели'

homepage/views.py
from django.shortcuts import render
from meta.views import Meta

from homepage.models import CarouselImg
from product.models import Type


def index(request):
    template_name = 'homepage/index.html'

    protocol = request.scheme
    host = request.get_host()
    base_url = f'{protocol}://{host}'

    meta = Meta(
        title='Производитель огнеупорных и изоляционных материалов КЕРАТЕХ',
        description='Огнеупорные и изоляционные материалы КЕРАТЕХ с доставкой '
        'по РФ. Вся продукция соответствует международным стандартам. Качество'
        ' и надежность. Современные огнеупорные технологии для повышения '
        'эффективности и конкурентоспособности. Для заказа огнеупорных '
        'материалов звоните +79507587027.',
        keywords=[
            'КЕРАТЕХ', 'огнеупорные материалы', 'изоляционные материалы',
            'сталеразливка', 'доставка по РФ', 'международные стандарты',
            'качество', 'надежность', 'современные технологии',
        ],
        url=request.build_absolute_uri(),
        object_type='Organization',
        site_name='Keratech',
        schemaorg_type='Organization',
        schemaorg_title='Keratech',
        use_json_ld=True,
        schema={
            '@context': 'https://schema.org',
            '@type': 'Organization',
            'image': f'{base_url}/static/favicon/logo_text.svg',
            'url': base_url,
            'logo': f'{base_url}/static/favicon/logo_text.svg',
            'name': 'Supplier of refractory and insulating materials '
                    'KERATECH.',
            'description': 'Fireproof and insulating materials KERATECH with '
                    'delivery in Russia. All products meet international '
                    'standards. Quality and reliability. Modern refractory '
                    'technologies to increase efficiency and competitiveness. '
                    'To order refractory materials call +79507587027.',
            'email': 'keratekh@yandex.ru',
            'telephone': '+7-950-758-70-27',
        }
    )

    carousel_imgs = CarouselImg.objects.all()
    types = Type.objects.all()

    context = {
        'meta': meta,
        'types': types,
        'carousel_imgs': carousel_imgs,
    }

    return render(request, template_name, context)

templates/homepage/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<link href="{% static 'apps/homepage/index.css' %}" rel="stylesheet">

<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      {% if carousel_imgs|length > 1 %}
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-label="Slide 1"></button>
        {% for carousel_img in carousel_imgs|slice:"1:"  %}
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="{{ forloop.counter }}" aria-label="Slide {{ forloop.counter|add:1 }}"></button>
        {% endfor %}
      {% endif %}
    </div>
    <div class="carousel-inner">
      {% if carousel_imgs %}
      <div class="carousel-item active">
        <img src="{{ carousel_imgs.0.photo.url }}" alt="Фото организации">
      </div>

      {% for carousel_img in carousel_imgs|slice:"1:" %}
        <div class="carousel-item">
          <img src="{{ carousel_img.photo.url }}" alt="Фото организации">
        </div>
      {% endfor %}
      {% else %}
         <h1 class="text-center">На данный момент в карусели нет фото</h1>
      {% endif %}
    </div>
    {% if carousel_imgs|length > 1 %}
      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    {% endif %}
</div>

<h1 class="text-center py-3">Продукция от Кератех:</h1>

<div class="container p-5 text">
  {% if types %}
    {% for type in types %}
      <div class="row featurette">
        {% if forloop.counter|divisibleby:2 %}
          <div class="col-md-7 order-md-2">
        {% else %}
          <div class="col-md-7">
        {% endif %}
            <h2 class="featurette-heading fw-normal lh-1">{{ type.title }}</h2>
            <p class="lead">{{ type.description|safe}}</p>
          </div>
        
        {% if forloop.counter|divisibleby:2 %}
          <div class="col-md-5 order-md-1">
        {% else %}
          <div class="col-md-5">
        {% endif %}
            <a href="{% url 'product:type_detail' type.slug %}">
              <img src="{{ type.photo.url }}" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" alt="Фото типа продукции">
            </a>
          </div>
      </div>

      <hr class="featurette-divider p-5">

    {% endfor %}
  {% else %}
    <h1 class="text-center">На данный момент нет типов продукции</h1>
  {% endif %}
</div>

{% endblock %}