Keratech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from .sitemaps import ProductSitemap, StaticViewSitemap, TypeSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'types': TypeSitemap,
    'products': ProductSitemap,
}

handler404 = 'core.views.error_404'

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
    ),

    path(
        'chaining/',
        include('smart_selects.urls'),
    ),
    path(
        'ckeditor/',
        include('ckeditor_uploader.urls'),
    ),
    path(
        'djeym/',
        include('djeym.urls', namespace='djeym'),
    ),

    path(
        '',
        include('homepage.urls'),
        name='homepage',
    ),
    path(
        'product/',
        include('product.urls'),
        name='product',
    ),
    path(
        'about/', include('about.urls'),
        name='about',
    ),

    path(
        '', include('core.urls'),
        name='core',
    ),
    path(
        'sitemap.xml',
        sitemap, {'sitemaps': sitemaps},
    )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

about/urls.py
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('', views.index, name='index'),
]

core/urls.py
from django.urls import path

from core import views

urlpatterns = [
    path('robots.txt', views.robots_txt, name='robots_txt'),
]

homepage/urls.py
from django.urls import path

from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

product/urls.py
from django.urls import path

from product import views

app_name = 'product'

urlpatterns = [
    path('type/<slug:slug>/', views.type_detail, name='type_detail'),
    path('', views.product_list, name='product_list'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

templates/includes/footer.html
{% load static %}


<footer class="py-3 my-4">
    <p class="text-center text-body-secondary border-top py-3">© {% now "Y" %} ООО Кератех</p>
</footer>

templates/includes/header.html
{% load static %}
<link href="{% static 'apps/includes/header.css' %}" rel="stylesheet">

<header class="position-fixed">
  <nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand mobile" href="{% url 'homepage:index' %}">
        <img class="logo" src="{% static 'favicon/logo_text.svg' %}" width="70px" height="70px" alt="Кератех">
      </a>
      <button class="navbar-toggler border-0 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button> 
      <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img class="logo" src="{% static 'favicon/logo_text.svg' %}" width="80px" height="80px" alt="Кератех">
      </a>
      <div class="collapse navbar-collapse align-self-center" id="navbarNavAltMarkup">
        <div class="navbar-nav text-center">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage:index' %}" style="color: #5cb3e2">Главная</a>
          <a class="nav-link active" aria-current="page" href="{% url 'product:product_list' %}" style="color: #5cb3e2">Продукты</a>
          <a class="nav-link active" aria-current="page" href="{% url 'about:index' %}" style="color: #5cb3e2">Контакты</a>
          <a class="nav-link active" data-bs-toggle="modal" data-bs-target="#exampleModal" style="color: #ffab24">Связаться</a>
        </div>
      </div>
    </div>
  </nav>
</header>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Cвяжитесь с нами! </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% include 'includes/contact_form.html' with form=contact_form %}
          <div class="text-center m-2">
            <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
              Назад
            </button>
            <button class="btn btn-primary" type="submit">Искать</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button type="button" class="btn btn-primary">Отправить</button>
      </div>
    </div>
  </div>
</div>

templates/includes/product_card.html
{% load static %}

<link href="{% static 'apps/includes/product_card.css' %}" rel="stylesheet">

<div class="card">
    <a href="{% url 'product:product_detail' product.slug %}">
      <div id="carouselIndicators{{ product_id }}" class="card-img-top carousel slide" data-bs-ride="true">
        <div class="carousel-indicators">
          {% if images|length > 0 %}
            <button type="button" data-bs-target="#carouselIndicators{{ product_id }}" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            {% for image in images %}
              <button type="button" data-bs-target="#carouselIndicators{{ product_id }}" data-bs-slide-to="{{ forloop.counter }}" aria-label="Slide {{ forloop.counter }}"></button>
            {% endfor %}
          {% endif %}
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{ product.photo.url }}" alt="Фото продукта">
          </div>
          {% for image in images %}
            <div class="carousel-item">
              <img src="{{ image }}" alt="Фото продукта">
            </div>
          {% endfor %}
        </div>
        {% if images|length > 0 %}
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselIndicators{{ product_id }}" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselIndicators{{ product_id }}" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        {% endif %}
      </div>
    </a>

    <div class="card-body">
      <h5 class="card-title">{{ product.title }}</h5>
    </div>

    <div class="card-footer">
      <a class="btn" href="{% url 'product:product_detail' product.slug %}" role="button" style="color: #5cb3e2;">Подробнее</a>
    </div>
</div>